### ISSUE TITLE
MetaData Streams Name

### ISSUE THREAD

**Issue by kevthehermit** [crackinglandia/pype32#9]
There are some malware samples that use #- instead of #~ and still operate correctly.
pype32 can not handle these files. 

```
>>> pe = pype32.PE('Lum_1.exe')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pype32\pype32.py", line 126, in __init__
    self._internalParse(rd)
  File "C:\Python27\lib\site-packages\pype32\pype32.py", line 493, in _internalParse
    self._parseDirectories(self.ntHeaders.optionalHeader.dataDirectory, self.PE_TYPE)
  File "C:\Python27\lib\site-packages\pype32\pype32.py", line 938, in _parseDirectories
    dataDirectoryInstance[directory[0]].info = directory[1](dir.rva.value, dir.size.value, magic)
  File "C:\Python27\lib\site-packages\pype32\pype32.py", line 1429, in _parseNetDirectory
    for i in netDirectoryClass.netMetaDataStreams["#~"].info.tables["ManifestResource"]:
KeyError: '#~'
>>>
```

WARNING LIVE MALWARE

Have provided a sample for Testing FileName 'Lum_1.exe'

http://repo.doesntexist.com/public.php?service=files&t=1bf02f3de6eae2762f9c8304fc0af29f

**Comment by poxyran** [comment]
We can read the value from the file and put it as the key for the dict but I think it is a nasty hack, what do you think @snemes ?

**Comment by snemes** [comment]
Modified the code to use the stream's ordinal number instead of the steam name. It is a dirty fix, so if it turns out that there are certain .NET assemblies which store Metadata streams in a different order, then we will have to further tweak the logic. I also added support for some new Metadata table types (which I was unaware of - as they were not in the official .NET documentation) to allow loading the particular file mentioned above.

**Comment by poxyran** [comment]
Thanks @snemes for the fix. @kevthehermit would you try it again? If it works, then I'll close the issue.

**Comment by kevthehermit** [comment]
The fixes are working perfectly. Thanks to all
